[package]
name = "stun"
version = "0.1.0"
edition = "2024"

[dependencies]
bytes = { version = "1.11.1", default-features = false, optional = true }
crc = { version = "3.4.0", default-features = false, optional = true }
rand = { version = "0.10.1", default-features = false, optional = true }
sha1 = { version = "0.11.0", default-features = false, optional = true }
zerocopy = { version = "0.8.50", default-features = false, features = ["derive"] }

[features]
alloc = ["sha1/alloc"]
std = ["alloc", "zerocopy/std", "rand/std", "bytes/std"]
rand = ["dep:rand", "rand/thread_rng"]
sha1 = ["dep:sha1"]
crc = ["dep:crc"]
bytes = ["dep:bytes"]

default = ["std", "rand", "sha1", "crc", "bytes"]
