services:
  hub:
    build: ./hub
    networks:
      - back
  bind:
    build: ./bind
    networks:
      - back
    depends_on:
      - hub
  frontend:
    build:
      context: ./
      dockerfile: ./frontend/Dockerfile
    networks:
      - back
      - front
    ports:
      - 80:80
      - 443:443
      - 443:443/udp

networks:
  front: {}
  back:
    internal: true
