name: switchboard
services:
  coturn:
    build: ./coturn
    ports:
      - 3478:3478/tcp
      - 3478:3478/udp
  bind:
    build: ./bind
    ports:
      - 80:80/udp
  tcptump:
    build: ./tcpdump
