[package]
name = "turnserver"
version = "0.1.0"
edition = "2024"
license = "MIT-0"

[dependencies]
bytes = "1.11.1"
clap = { version = "4.4", features = ["derive"] }
common = { path = "../common" }
eyre = "0.6.12"
ipnet = "2.12.0"
mio = { version = "1.2.1", features = ["os-poll", "os-ext", "net"] }
slab = "0.4.12"
stun = { path = "../stun" }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
tun-rs = "2.8.3"
zerocopy = { version = "0.8.50", features = ["derive"] }
