[package]
name = "turnserver"
version = "0.1.0"
edition = "2024"
license = "MIT-0"

[dependencies]
bytes = "1.11.1"
clap = { version = "4.4", features = ["derive"] }
eyre = "0.6.12"
ipnet = "2.12.0"
stun = { path = "../stun" }
tun-rs = "2.8.3"
zerocopy = { version = "0.8.50", features = ["derive"] }
