#!/usr/sbin/nft -f

flush ruleset

table inet dont_track {
	chain prerouting {
		type filter hook prerouting priority -300;
		meta nfproto ipv4 notrack
		meta nfproto ipv6 meta l4proto != udp notrack
		udp dport != 3478 notrack
		# Don't track binding requests (to preserve the original sender's ip+port for xor-mapped)
		@th,64,16 == 0x0001 \
		@th,96,32 == 0x2112A442 \
		notrack
	}
	chain output {
		type filter hook output priority -300;
		meta l4proto != udp notrack
		udp sport != 3478 notrack

		# Don't track binding responses
		@th,64,16 == 0x0101 \
		@th,96,32 == 0x2112A442 \
		notrack
	}
}

table ip6 swbrd {
	chain dissolve {
		type filter hook prerouting priority mangle;
		meta l4proto udp \
		@th,64,16 == 0x0001 \
		@th,96,32 == 0x2112A442 \
		@th,224,16 == 0x0006 \
		@th,256,64 == 0x646973736f6c7665 \
		@th,320,8 == 0x3a \
		meta mark set 0x1
	}
	chain allocate {
		# STUN allocate requests from ipv6 peers get mapped into our pool
		type nat hook input priority srcnat;
		meta l4proto udp \
		udp dport 3478 \
		@th,64,16 == 0x0003 \
		@th,96,32 == 0x2112A442 \
		snat to ::3478:0:0/96
	}
}
