# Anonymous credentials used by switchboard addresses
realm=none
user=guest:the/guest/turn/credential/constant
lt-cred-mech

# Disable permission checks
# server-relay

# Disable unused stuff
no-tls
no-dtls
no-cli
no-tcp-relay
