#!/bin/sh
set -e

case "$1" in
remove)
	[ -d /run/systemd/system ] || exit 0
	systemctl --system daemon-reload >/dev/null || true
	deb-systemd-helper mask dtls-proxy.service >/dev/null || true
	networkctl reload >/dev/null 2>&1 || true
	networkctl delete dtls-proxy >/dev/null 2>&1 || true
	;;
purge)
	deb-systemd-helper purge dtls-proxy.service >/dev/null || true
	deb-systemd-helper unmask dtls-proxy.service >/dev/null || true
	;;
esac
exit 0
