#!/bin/sh
set -e

case "$1" in
remove)
	[ -d /run/systemd/system ] || exit 0
	systemctl --system daemon-reload >/dev/null || true
	deb-systemd-helper mask swbrd-ext-echo.service >/dev/null || true
	;;
purge)
	deb-systemd-helper purge swbrd-ext-echo.service >/dev/null || true
	deb-systemd-helper unmask swbrd-ext-echo.service >/dev/null || true
	;;
esac
exit 0
