# This is to fix ip_transparent->localhost connections
net.ipv4.conf.all.route_localnet = 1
# This is to divert ICE dissolve packets even if they match a connected socket (which normally caches the destination in the skb instead of doing a route lookup)
net.ipv4.udp_early_demux = 0
