name: Docker Image CI

on:
  push:
    branches: [ "dev" ]

jobs:

  docker:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - uses: docker/login-action
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - uses: docker/build-push-action
      with:
        push: true
        context: ./hub
        tags: ghcr.io/evan-brass/swbrd-hub:latest
